version: '3'

services:
  main-fns:
    build: .
    container_name: 'main-fns'
    working_dir: '/usr/src/app'
    volumes:
      - ./:/usr/src/app:rw,Z
      - ~/.gitconfig:/etc/gitconfig
    tty: true
