name: Test

on: 
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run test and linter
      run: npm run test:all
    
    - name: Upload coverage to codecov
      run: npx codecov --token=${{ secrets.CODECOV_TOKEN }}